{
    "comments": [
        {
            "author": null,
            "body": "Added a null check in the relevant method, which will generate a new date \nobject only if needed.  I wonder why the lifecycle start wasn't taking care of \nthis.",
            "date": "20040115T16:20:59",
            "id": 0
        }
    ],
    "component": "Catalina:Modules",
    "description": "context.xml contains a AccessLogValve. After \"install\" (via ant task) everything\nworks. A subsequent \"remove\" and \"install\" of the same webapp cause the error\nbelow after pressing the reload button  in an existing session in the client\nbrowser:\n\n15.01.2004 16:39:50 org.apache.coyote.tomcat5.CoyoteAdapter service\nSCHWERWIEGEND: An exception or error occurred in the container during the\nrequest processing\njava.lang.NullPointerException\n        at\norg.apache.catalina.valves.AccessLogValve.getDate(AccessLogValve.java:1030)\n        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:589)\n        at\norg.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:149)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:195)\n        at\norg.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:151)\n        at\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:164)\n        at\norg.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:149)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:564)\n        at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:156)\n        at\norg.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:151)\n        at\norg.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:564)\n        at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:972)\n        at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:211)\n        at\norg.apache.coyote.http11.Http11Processor.process(Http11Processor.java:805)\n        at\norg.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:696)\n        at\norg.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:605)\n        at\norg.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:677)\n        at java.lang.Thread.run(Thread.java:534)\n\nLooks like currentDate is not initialized under certain circumstances.",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "26171",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P3 normal",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "NullPointerException in AccessLogValve",
    "systemSpecification": true,
    "version": "5.0.16"
}