{
    "comments": [
        {
            "author": null,
            "body": "Created attachment 13478\nFix InvalidNameException if LDAP DN contains slash character\n\nTested with Tomcat 5.0.28 and 5.0.29",
            "date": "20041117T11:03:09",
            "id": 0
        },
        {
            "author": null,
            "body": "Done for 5.0.30.",
            "date": "20041119T16:01:44",
            "id": 1
        },
        {
            "author": null,
            "body": "And for 5.5.5.  Thank you for submitting this patch.",
            "date": "20041119T16:08:39",
            "id": 2
        },
        {
            "author": null,
            "body": "The first login attempt each day fails because the LDAP server has closed the connection which has \nbeen idle for a time. Obviously the previous fix only fixed it for some situations or something has \nchanged. We are running Tomcat 5.5.15\n\nApr 17, 2007 8:18:38 AM org.apache.catalina.realm.JNDIRealm authenticate\nSEVERE: Exception performing authentication\njavax.naming.ServiceUnavailableException: public.ldap.uq.edu.au:389; socket closed; remaining name \n'ou=People,o=xxx,c=AU'\n        at com.sun.jndi.ldap.Connection.readReply(Connection.java:410)\n        at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:340)\n        at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:170)\n        at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2637)\n        at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2546)\n        at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2520)\n        at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1901)\n        at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1806)\n        at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1731)\n        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:368)\n        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:\n338)\n        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:\n321)\n        at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:248)\n        at org.apache.catalina.realm.JNDIRealm.getUserBySearch(JNDIRealm.java:1055)\n        at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:958)\n        at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:907)\n        at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:808)\n        at org.apache.catalina.authenticator.FormAuthenticator.authenticate(FormAuthenticator.java:257)\n        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:416)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:199)\n        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:282)\n        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:754)\n        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:684)\n        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:876)\n        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)\n        at java.lang.Thread.run(Thread.java:595)\n",
            "date": "20070417T17:01:59",
            "id": 3
        },
        {
            "author": null,
            "body": "(In reply to comment #4)\n> The first login attempt each day fails because the LDAP server has closed the connection which has \n> been idle for a time. Obviously the previous fix only fixed it for some situations or something has \n> changed. We are running Tomcat 5.5.15\n> \n> Apr 17, 2007 8:18:38 AM org.apache.catalina.realm.JNDIRealm authenticate\n> SEVERE: Exception performing authentication\n> javax.naming.ServiceUnavailableException: public.ldap.uq.edu.au:389; socket closed; remaining \nname \n> 'ou=People,o=xxx,c=AU'\n>         at com.sun.jndi.ldap.Connection.readReply(Connection.java:410)\n>         at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:340)\n>         at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:170)\n>         at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2637)\n>         at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2546)\n>         at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2520)\n>         at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1901)\n>         at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1806)\n>         at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1731)\n>         at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:368)\n>         at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:\n> 338)\n>         at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:\n> 321)\n>         at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:248)\n>         at org.apache.catalina.realm.JNDIRealm.getUserBySearch(JNDIRealm.java:1055)\n>         at org.apache.catalina.realm.JNDIRealm.getUser(JNDIRealm.java:958)\n>         at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:907)\n>         at org.apache.catalina.realm.JNDIRealm.authenticate(JNDIRealm.java:808)\n>         at org.apache.catalina.authenticator.FormAuthenticator.authenticate(FormAuthenticator.java:\n257)\n>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:416)\n>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n>         at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:199)\n>         at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:282)\n>         at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:754)\n>         at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:684)\n>         at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:876)\n>         at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)\n>         at java.lang.Thread.run(Thread.java:595)\n> \n\nSorry filed incorrectly\n\nJZ",
            "date": "20070417T17:04:39",
            "id": 4
        }
    ],
    "component": "Catalina:Modules",
    "description": "JNDIRealm is for authenticating users from an LDAP Directory.\n\nIt fails with InvalidNameException for users with a slash or\ndouble quote character in the users LDAP DN, like for example:\n\ncn=Test User,ou=Department A/B,dc=example,dc=de\n\nThis applies to Tomcat 5.0.29, 5.0.28 and all version using\nthe same JNDIRealm code.\n\nBackground:\nSlash characters are perfectly valid characters for LDAP attribute\nstring and don't have to be escaped.\nDouble quotes have to be escaped but should not be a problem either.\nThere may be more character problems which should be fixed by the patch.\n\nThe problem is caused by the JNDI API where searchResult.getName()\ndoes not return a string representation of an LDAP relative distinguished\nname but a string representation of a CompositeName, containing one\nor more LdapNames. This is not documented.\n\nFix idea in short:\nreplace \n Name entryName = parser.parse(result.getName());\nwith\n Name entryName = parser.parse(new CompositeName(result.getName()).get(0));\n\nFrerk Meyer",
    "hasPatch": true,
    "hasScreenshot": false,
    "id": "32269",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P2 normal",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "[PATCH] JNDIRealm fails with InvalidNameException to authenticate users if LDAP distinguished name (DN) contains slash or double quote character(s)",
    "systemSpecification": false,
    "version": "5.0.29"
}