{
    "comments": [
        {
            "author": null,
            "body": "This has been fixed in 5.5.11.",
            "date": "20050922T19:24:46",
            "id": 0
        }
    ],
    "component": "Catalina",
    "description": "We're coding up special handling for \"connection reset by peer\" messages in Wicket.\n\nCurrently ClientAbortException does not override getCause() to return\ngetThrowable(). This makes it difficult for Wicket to safely intercept\n\"connection reset by peer\" messages since we cannot catch ClientAbortException\n(which is Tomcat-specific) and we are forced to parse Exception.getMessage() for\n\"connection reset by peer\". This is error-prone because we want to rely as\nlittle as possible on the contents of the message -- different JVMs throw\ndifferent messages sometimes.\n\nCan you please try fixing this for the next release?",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "35984",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P2 normal",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "ClientAbortException should override getCause()",
    "systemSpecification": false,
    "version": "5.5.9"
}