{
    "comments": [
        {
            "author": null,
            "body": "same here for me with 5.5.17 on Linux. Same setup on the webapp side used to\nwork find in 5.5.12.",
            "date": "20060601T19:30:03",
            "id": 0
        },
        {
            "author": null,
            "body": "(In reply to comment #1)\n> same here for me with 5.5.17 on Linux. Same setup on the webapp side used to\n> work find in 5.5.12.\n\ndid you tried with 5.5.16 ?",
            "date": "20060602T05:48:31",
            "id": 1
        },
        {
            "author": null,
            "body": "It seems that you have a log4j classloader issuse.\n\nI hope you only have a log4j jar and commons-logging inside you app and not at common/lib.\n\nTest it with 5.5.17 again.",
            "date": "20060602T06:12:28",
            "id": 2
        },
        {
            "author": null,
            "body": "(In reply to comment #3)\n> It seems that you have a log4j classloader issuse.\n> \n> I hope you only have a log4j jar and commons-logging inside you app and not at\ncommon/lib.\n> \n> Test it with 5.5.17 again.\n\nsame isusue after removing commons-logging and log4j (renamed log4j.jar ->\nlog4j.jar.not and the same for commons-logging.jar) in common/lib (i use log4j\nto log tomcat message, not only in webapps...\n\nany idea ?",
            "date": "20060602T08:20:41",
            "id": 3
        },
        {
            "author": null,
            "body": "(In reply to comment #2)\n\n> \n> did you tried with 5.5.16 ?\n\n\nno, I haven't.",
            "date": "20060602T11:24:44",
            "id": 4
        },
        {
            "author": null,
            "body": "(In reply to comment #3)\n> It seems that you have a log4j classloader issuse.\n> \n> I hope you only have a log4j jar and commons-logging inside you app and not at\ncommon/lib.\n> \n> Test it with 5.5.17 again.\n\nJust as comment 4, I as well took out log4j and commons-logging from  common/lib\nand got the same behavior as before. As Christophe mentioned in comment 0, the\nredeploy works fine if the <Cluster> element is commented out.",
            "date": "20060602T11:26:59",
            "id": 5
        },
        {
            "author": null,
            "body": "(In reply to comment #4)\n\n> \n> i use log4j to log tomcat message, not only in webapps...\n> \n\nI use log4j for the same purpose.\n",
            "date": "20060602T11:27:59",
            "id": 6
        },
        {
            "author": null,
            "body": "(In reply to comment #7)\n> (In reply to comment #4)\n> \n> > \n> > i use log4j to log tomcat message, not only in webapps...\n> > \n> \n> I use log4j for the same purpose.\n> \n\ngot the same in 5.5.16...\ndo you know where can i found 5.5.12 ?\n\nthanks in advance.",
            "date": "20060602T12:07:33",
            "id": 7
        },
        {
            "author": null,
            "body": "(In reply to comment #8)\n> \n> got the same in 5.5.16...\n> do you know where can i found 5.5.12 ?\n> \n> thanks in advance.\n\nTry:\nhttp://archive.apache.org/dist/jakarta/tomcat-5/v5.5.12/bin/",
            "date": "20060602T12:12:39",
            "id": 8
        },
        {
            "author": null,
            "body": "(In reply to comment #9)\n> (In reply to comment #8)\n> > \n> > got the same in 5.5.16...\n> > do you know where can i found 5.5.12 ?\n> > \n> > thanks in advance.\n> \n> Try:\n> http://archive.apache.org/dist/jakarta/tomcat-5/v5.5.12/bin/\nthanks.\n\nOk, i just tried with 5.5.12 it's ok, no issue...\ni have also tried with others versions :\n\n5.5.12 : ok\n5.5.13 : BUG\n5.5.16 : BUG\n5.5.17 : BUG \n\nit appears that there was a change from 5.5.13 ...\n",
            "date": "20060602T13:24:34",
            "id": 9
        },
        {
            "author": null,
            "body": "(In reply to comment #10)\n> \n> Ok, i just tried with 5.5.12 it's ok, no issue...\n> i have also tried with others versions :\n> \n> 5.5.12 : ok\n> 5.5.13 : BUG\n> 5.5.16 : BUG\n> 5.5.17 : BUG \n> \n> it appears that there was a change from 5.5.13 ...\n> \n\nI have 5.5.12 in production with no problems. And yes, 5.5.13 causes the bug to\nappear for me as well. So, something changed from 5.5.12 -> 5.5.13. Time to look\nat the changelog for 5.5.13.",
            "date": "20060602T13:48:37",
            "id": 10
        },
        {
            "author": null,
            "body": "(In reply to comment #11)\n> \n> I have 5.5.12 in production with no problems. And yes, 5.5.13 causes the bug to\n> appear for me as well. So, something changed from 5.5.12 -> 5.5.13. Time to look\n> at the changelog for 5.5.13.\n\nI didn't see anything in the 5.5.13 changelog (with my untrained eye). However,\nthis discussion seems to be similar.\n\nhttp://www.nabble.com/RE%3A-Tomcat-5.5.15-Context-Reloading-issue-t1123634.html#a3010048\n\nR\u00e9my?\n\nIn that thread R\u00e9my says:\n\n    I added some code to null out certain instances, and your shared log4j\n    setup doesn't like it (at least it's a likely possibility). Try to use\n    a JNDI based log4j setup (or similar, using one logging namespace for\n    all webapps is not clean), or don't share it. \n\nWould it be possible to see where is the code which nulls out certain instances??\n\nThe precursor the above thread is at:\nhttp://www.nabble.com/Tomcat-5.5.15-Context-Reloading-issue-t1076386.html#a2955863\n\nBe aware that in comment 4 and comment 6, both Christophe and I have reported\nthat even with nothing in common/lib (no log4j.jar, no commons-logging.jar), we\nstill get the bug. The only log4j.jar and commons-logging.jar is the one present\nin WEB-INF/lib of the webapp. So, more than likely the \"shared log4j\" setup is\nnot the culprit.",
            "date": "20060602T14:15:18",
            "id": 11
        },
        {
            "author": null,
            "body": "(In reply to comment #12)\n> (In reply to comment #11)\n> > \n> > I have 5.5.12 in production with no problems. And yes, 5.5.13 causes the bug to\n> > appear for me as well. So, something changed from 5.5.12 -> 5.5.13. Time to look\n> > at the changelog for 5.5.13.\n> \n> I didn't see anything in the 5.5.13 changelog (with my untrained eye). However,\n> this discussion seems to be similar.\n> \n>\nhttp://www.nabble.com/RE%3A-Tomcat-5.5.15-Context-Reloading-issue-t1123634.html#a3010048\n> \n> R\u00e9my?\n> \n> In that thread R\u00e9my says:\n> \n>     I added some code to null out certain instances, and your shared log4j\n>     setup doesn't like it (at least it's a likely possibility). Try to use\n>     a JNDI based log4j setup (or similar, using one logging namespace for\n>     all webapps is not clean), or don't share it. \n> \n> Would it be possible to see where is the code which nulls out certain instances??\n> \n> The precursor the above thread is at:\n> http://www.nabble.com/Tomcat-5.5.15-Context-Reloading-issue-t1076386.html#a2955863\n> \n> Be aware that in comment 4 and comment 6, both Christophe and I have reported\n> that even with nothing in common/lib (no log4j.jar, no commons-logging.jar), we\n> still get the bug. The only log4j.jar and commons-logging.jar is the one present\n> in WEB-INF/lib of the webapp. So, more than likely the \"shared log4j\" setup is\n> not the culprit.\n\n\n\nin 5.5.12, deploy is ok, but i get this recurrent error in log :\n----------------------\n ERROR org.apache.catalina.cluster.tcp.TcpReplicationThread[3]\norg.apache.catalina.cluster.tcp.TcpReplicationThread -\n TCP Worker thread in cluster caught 'java.io.IOException: Connection reset by\npeer' closing channel\n java.io.IOException: Connection reset by peer\n        at sun.nio.ch.FileDispatcher.read0(Native Method)\n        at sun.nio.ch.SocketDispatcher.read(Unknown Source)\n        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)\n        at sun.nio.ch.IOUtil.read(Unknown Source)\n        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)\n        at\norg.apache.catalina.cluster.tcp.TcpReplicationThread.drainChannel(TcpReplicationThread.java:125)\n        at\norg.apache.catalina.cluster.tcp.TcpReplicationThread.run(TcpReplicationThread.java:69)\nERROR org.apache.catalina.cluster.tcp.TcpReplicationThread[3]\norg.apache.catalina.cluster.tcp.TcpReplicationThread -\nTCP Worker thread in cluster caught 'java.io.IOException: Connection reset by\npeer' closing channel\n java.io.IOException: Connection reset by peer\n        at sun.nio.ch.FileDispatcher.read0(Native Method)\n        at sun.nio.ch.SocketDispatcher.read(Unknown Source)\n        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)\n        at sun.nio.ch.IOUtil.read(Unknown Source)\n        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)\n        at\norg.apache.catalina.cluster.tcp.TcpReplicationThread.drainChannel(TcpReplicationThread.java:125)\n        at\norg.apache.catalina.cluster.tcp.TcpReplicationThread.run(TcpReplicationThread.java:69)\n--------------------",
            "date": "20060602T14:25:18",
            "id": 12
        },
        {
            "author": null,
            "body": "(In reply to comment #13)\n> \n> \n> in 5.5.12, deploy is ok, but i get this recurrent error in log :\n>\n\nThat looks like bug 38788, so its a separate issue.",
            "date": "20060602T14:42:40",
            "id": 13
        },
        {
            "author": null,
            "body": "(In reply to comment #14)\n> (In reply to comment #13)\n> > \n> > \n> > in 5.5.12, deploy is ok, but i get this recurrent error in log :\n> >\n> \n> That looks like bug 38788, so its a separate issue.\n\nok...\ni didn't know...",
            "date": "20060602T18:24:31",
            "id": 14
        },
        {
            "author": null,
            "body": "please attach a test case, that way we can get the facts and fix it more promptly.",
            "date": "20060602T21:55:03",
            "id": 15
        },
        {
            "author": null,
            "body": "(In reply to comment #16)\n> please attach a test case, that way we can get the facts and fix it more promptly.\n\nsorry, but what do you mean with a 'test case'?\n\nYou can reproduce the problem with the server.xml in my first post (a simple\ncluster configuration is sufficient (<SimpleTcpCluster line only is sufficient)\nand try to deploy with html manager or copy a war to your webapps (with\nautodeploy enabled of course). \n\n",
            "date": "20060603T07:39:18",
            "id": 16
        },
        {
            "author": null,
            "body": "test case, meaning maybe a zip containing your config files, any modifications\nthat you have made two tomcat, ie, added in log4j etc.\n\nie, can you get us detailed instructions on how to exactly reproduce your\nproblem. just saying that deploy an app and it breaks, it simply not sufficient,\nas our apps are deploying.",
            "date": "20060603T15:42:03",
            "id": 17
        },
        {
            "author": null,
            "body": "(In reply to comment #18)\n> test case, meaning maybe a zip containing your config files, any modifications\n> that you have made two tomcat, ie, added in log4j etc.\n> \n> ie, can you get us detailed instructions on how to exactly reproduce your\n> problem. just saying that deploy an app and it breaks, it simply not sufficient,\n> as our apps are deploying.\n\nI have made some progress with a \"simple\" test case. Here are the steps:\n\n1) download vanilla tomcat .tar.gz (5.5.17)\n2) tar xzvf /home/haroon/src/dist/apache-tomcat-5.5.17.tar.gz\n3) cd apache-tomcat-5.5.17/conf/\n4) edit server.xml to uncomment the <Cluster> config (leave everything else as is)\n5) edit tomcat-users.xml so that you have a username/password with role \"manager\"\n6) cd ../bin\n7) ./startup.sh\n8) After tomcat starts up, deploy testcase by copying\nservlets-examples-cluster-node1.war to ../webapps (I will attach .war file in\nnext comment)\n9) context deploys fine\n10) go to http://localhost:8080/manager/html/list in your browser\n11) Watch your catalina.out as you click on Reload for\nservlets-examples-cluster-node1 and get the error.\n\nQuestions?\n",
            "date": "20060605T20:57:19",
            "id": 18
        },
        {
            "author": null,
            "body": "Created attachment 18406\ntestcase describing cluster related reload of distributable webapps which contain log4j",
            "date": "20060605T20:58:49",
            "id": 19
        },
        {
            "author": null,
            "body": "(In reply to comment #20)\n\n> testcase describing cluster related reload of distributable webapps which\n> contain log4j\n> \n\nTo give you some information about how I created this \"sample testcase\" app.\n\n* I obtained the file from\nhttp://opensource.atlassian.com/confluence/oss/pages/viewpageattachments.action?pageId=2578\nwhich is a page for listing the attachments for the wiki article at:\nhttp://opensource.atlassian.com/confluence/oss/display/GERONIMO/Geronimo+Clustering+Example\n\n* After that I added a simple log4j.properties in WEB-INF/classes\n\n---begin-----\n# This is the configuration for logging displayed in the Application Server\nlog4j.rootLogger=INFO, stdout\n\nlog4j.appender.stdout=org.apache.log4j.ConsoleAppender\nlog4j.appender.stdout.layout=org.apache.log4j.PatternLayout\n\n# Pattern to output the caller's file name and line number.\nlog4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} %p [%t] %C{1}.%M(%L)\n|%m%n\n-----cut-----\n\n* copied commons-logging.jar (I think 1.0.4) and log4j-1.2.13.jar in WEB-INF/lib\n\nThat is the exact jar that you see in the attachment in the previous comment.",
            "date": "20060605T21:03:10",
            "id": 20
        },
        {
            "author": null,
            "body": "(In reply to comment #21)\n> \n> That is the exact jar that you see in the attachment in the previous comment.\n\noops... meant to say war file (instead of jar)",
            "date": "20060605T21:04:06",
            "id": 21
        },
        {
            "author": null,
            "body": "The issue is fairly obvious: the class uses a static logger (initialized with a\nrandom context class loader set) which is never reset, while it should be\nlogging to the log field inherited from ManagerBase.\n\n-> the solution is to remove:\n    public static org.apache.commons.logging.Log log =\norg.apache.commons.logging.LogFactory\n            .getLog(DeltaManager.class);\n",
            "date": "20060608T12:35:44",
            "id": 22
        },
        {
            "author": null,
            "body": "(In reply to comment #23)\n> The issue is fairly obvious: the class uses a static logger (initialized with a\n> random context class loader set) which is never reset, while it should be\n> logging to the log field inherited from ManagerBase.\n> \n> -> the solution is to remove:\n>     public static org.apache.commons.logging.Log log =\n> org.apache.commons.logging.LogFactory\n>             .getLog(DeltaManager.class);\n> \n\nI tried that. The problem did not go away. Same as before:\n\nlog4j:ERROR Error occured while converting date.\njava.lang.NullPointerException\n    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:488)\n    at java.lang.StringBuffer.append(StringBuffer.java:302)\n    at org.apache.log4j.helpers.ISO8601DateFormat.format(ISO8601DateFormat.java:132)\n    at java.text.DateFormat.format(DateFormat.java:314)\n    at\norg.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:444)\n    at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:64)\n    at org.apache.log4j.PatternLayout.format(PatternLayout.java:503)\n    at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:301)\n    at org.apache.log4j.WriterAppender.append(WriterAppender.java:159)\n    at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)\n    at\norg.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)\n    at org.apache.log4j.Category.callAppenders(Category.java:203)\n    at org.apache.log4j.Category.forcedLog(Category.java:388)\n    at org.apache.log4j.Category.log(Category.java:853)\n    at org.apache.commons.logging.impl.Log4JLogger.info(Log4JLogger.java:133)\n    at org.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:975)\n    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4137)\n    at org.apache.catalina.core.StandardContext.reload(StandardContext.java:2990)\n    at org.apache.catalina.manager.ManagerServlet.reload(ManagerServlet.java:906)\n    at\norg.apache.catalina.manager.HTMLManagerServlet.reload(HTMLManagerServlet.java:473)\n    at\norg.apache.catalina.manager.HTMLManagerServlet.doGet(HTMLManagerServlet.java:98)\n    at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)\n    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)\n    at\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)\n    at\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n    at\norg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)\n    at\norg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)\n    at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:524)\n    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n    at\norg.apache.catalina.cluster.tcp.ReplicationValve.invoke(ReplicationValve.java:346)\n    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n    at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n    at\norg.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:833)\n    at\norg.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:639)\n    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1285)\n    at java.lang.Thread.run(Thread.java:595)\nJun 8, 2006 9:55:08 AM org.apache.catalina.loader.WebappClassLoader loadClass\nINFO: Illegal access: this web application instance has been stopped already. \nCould not load org.apache.log4j.spi.VectorWriter.  The eventual following stack\ntrace is caused by an error thrown for debugging purposes as well as to attempt\nto terminate the thread which caused the illegal access, and has no functional\nimpact.\njava.lang.IllegalStateException\n    at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1238)\n    at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1198)\n    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)\n    at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:154)\n    at org.apache.log4j.Category.forcedLog(Category.java:388)\n    at org.apache.log4j.Category.log(Category.java:853)\n    at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:193)\n    at org.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:989)\n    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4137)\n    at org.apache.catalina.core.StandardContext.reload(StandardContext.java:2990)\n    at org.apache.catalina.manager.ManagerServlet.reload(ManagerServlet.java:906)\n    at\norg.apache.catalina.manager.HTMLManagerServlet.reload(HTMLManagerServlet.java:473)\n    at\norg.apache.catalina.manager.HTMLManagerServlet.doGet(HTMLManagerServlet.java:98)\n    at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)\n    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)\n    at\norg.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)\n    at\norg.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)\n    at\norg.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)\n    at\norg.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)\n    at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:524)\n    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n    at\norg.apache.catalina.cluster.tcp.ReplicationValve.invoke(ReplicationValve.java:346)\n    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n    at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n    at\norg.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:833)\n    at\norg.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:639)\n    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1285)\n    at java.lang.Thread.run(Thread.java:595)\nJun 8, 2006 9:55:08 AM org.apache.commons.modeler.Registry registerComponent\nSEVERE: Null component\nCatalina:type=JspMonitor,name=jsp,WebModule=//localhost/servlets-examples-cluster-node1,J2EEApplication=none,J2EEServer=none\n",
            "date": "20060608T14:14:27",
            "id": 23
        },
        {
            "author": null,
            "body": "(In reply to comment #24)\n> \n> I tried that. The problem did not go away. Same as before:\n> \n\nPlease also remember that the first error talks about Error occured while\nconverting date and my log4j.appender.stdout.layout.ConversionPattern does have\n%d{ISO8601}. Is that date not available or null?",
            "date": "20060608T14:16:38",
            "id": 24
        },
        {
            "author": null,
            "body": "Ok, I just told that to help, and beyond that I don't care at all. My workaround\nmay not work for a simple reload, though.",
            "date": "20060608T14:38:35",
            "id": 25
        },
        {
            "author": null,
            "body": "I'll look into it today",
            "date": "20060608T14:59:05",
            "id": 26
        },
        {
            "author": null,
            "body": "Ok, so my most likely better but still very similar workaround is to instantiate\nthe manager earlier.",
            "date": "20060608T15:00:41",
            "id": 27
        },
        {
            "author": null,
            "body": "Created attachment 18431\nPatched version of 5.5.17 catalina-cluster.jar",
            "date": "20060608T16:54:54",
            "id": 28
        },
        {
            "author": null,
            "body": "Thanks for the hint Remy, entirely the clusters fault as it was not setting the\ncontext class loader when loading the manager instances.\n\nI have attached a patched catalina-cluster.jar, can you please verify the fix.\nIt will also be included in the next release of Tomcat\n\nPlease let us know if this works for you.",
            "date": "20060608T16:55:15",
            "id": 29
        },
        {
            "author": null,
            "body": "(In reply to comment #30)\n> \n> Please let us know if this works for you.\n\nYes, it works for me with my sample testcase. Kudos to you guys for the quick\nfix. I will try it with my regular webapp and hopefully it will not have any\nproblems.\n\nChristophe, is your problem fixed?",
            "date": "20060608T17:01:44",
            "id": 30
        },
        {
            "author": null,
            "body": "i will test tomorrow...\n\n",
            "date": "20060608T17:40:00",
            "id": 31
        },
        {
            "author": null,
            "body": "(In reply to comment #31)\n> \n> Yes, it works for me with my sample testcase. Kudos to you guys for the quick\n> fix. I will try it with my regular webapp and hopefully it will not have any\n> problems.\n> \n\nPleased to report that my production webapp encountered no problems either with\nthe new jar.\n",
            "date": "20060608T21:25:12",
            "id": 32
        },
        {
            "author": null,
            "body": "(In reply to comment #30)\n> Thanks for the hint Remy, entirely the clusters fault as it was not setting the\n> context class loader when loading the manager instances.\n> \n> I have attached a patched catalina-cluster.jar, can you please verify the fix.\n> It will also be included in the next release of Tomcat\n> \n> Please let us know if this works for you.\n\nIf it works, I think backporting the change I did in the dev branch of Tomcat\nwould be a good idea. I don't think it's really the job of the manager\nimplementation to deal with context class loaders.\n",
            "date": "20060609T06:52:34",
            "id": 33
        },
        {
            "author": null,
            "body": "No more problem with the new jar !\n\nThank you very much for your very quick fix...\n",
            "date": "20060609T09:06:40",
            "id": 34
        }
    ],
    "component": "Catalina",
    "description": "Hi,\n\ni encounter a strange problem with my tomcat cluster and webapps deployment.\n\nserver.xml\n--------------------------------\n<Server port=\"8005\" shutdown=\"SHUTDOWN\">\n\n  <Listener className=\"org.apache.catalina.core.AprLifecycleListener\" />\n  <Listener className=\"org.apache.catalina.mbeans.ServerLifecycleListener\" />\n  <Listener\nclassName=\"org.apache.catalina.mbeans.GlobalResourcesLifecycleListener\" />\n  <Listener\nclassName=\"org.apache.catalina.storeconfig.StoreConfigLifecycleListener\"/>\n\n  <!-- Global JNDI resources -->\n  <GlobalNamingResources>\n\n    <Environment name=\"simpleValue\" type=\"java.lang.Integer\" value=\"30\"/>\n    <Resource name=\"UserDatabase\" auth=\"Container\"\n              type=\"org.apache.catalina.UserDatabase\"\n       description=\"User database that can be updated and saved\"\n           factory=\"org.apache.catalina.users.MemoryUserDatabaseFactory\"\n          pathname=\"conf/tomcat-users.xml\" />\n\n  </GlobalNamingResources>\n\n\n  <!-- Define the Tomcat Stand-Alone Service -->\n  <Service name=\"Catalina\">\n\n\n    <!-- Define a non-SSL HTTP/1.1 Connector on port 8080 -->\n    <Connector address=\"polen-integ\" port=\"8080\" maxHttpHeaderSize=\"8192\"\n               maxThreads=\"300\" minSpareThreads=\"25\" maxSpareThreads=\"100\"\n               enableLookups=\"false\" acceptCount=\"100\"\n               connectionTimeout=\"20000\" disableUploadTimeout=\"true\" />\n\n    <!-- Define an AJP 1.3 Connector on port 8009 -->\n    <Connector port=\"8009\"\n               address=\"polen-integ.sofinco.fr\"\n               minProcessors=\"20\" maxProcessors=\"0\" maxThreads=\"350\"\nminSpareThreads=\"50\" maxSpareThreads=\"100\"\n               enableLookups=\"false\" redirectPort=\"8080\" protocol=\"AJP/1.3\"\ndisableUploadTimeout=\"true\" />\n\n     <Engine name=\"Catalina\" defaultHost=\"localhost\" jvmRoute=\"uxdev103\" >\n\n      <Realm className=\"org.apache.catalina.realm.UserDatabaseRealm\"\nresourceName=\"UserDatabase\"/>\n\n      <Host name=\"localhost\" appBase=\"webapps\" unpackWARs=\"true\" autoDeploy=\"true\"\n       xmlValidation=\"false\" xmlNamespaceAware=\"false\" >\n\n <!-- Cluster Definition -->\n\n        <Cluster className=\"org.apache.catalina.cluster.tcp.SimpleTcpCluster\"\n                doClusterLog=\"true\" clusterLogName=\"clusterlog\"\n                expireSessionsOnShutdown=\"false\"\n                useDirtyFlag=\"true\"\n                notifyListenersOnReplication=\"true\">\n\n        <Membership className=\"org.apache.catalina.cluster.mcast.McastService\"\n                mcastAddr=\"228.0.0.4\"\n                mcastBindAddress=\"127.0.0.1\"\n                mcastClusterDomain=\"polen-integ\"\n                mcastPort=\"45564\"\n                mcastFrequency=\"1000\"\n                mcastDropTime=\"30000\"/>\n\n        <Receiver className=\"org.apache.catalina.cluster.tcp.ReplicationListener\"\n                tcpListenAddress=\"polen-integ\"\n                tcpSelectorTimeout=\"100\"\n                tcpThreadCount=\"6\"/>\n\n        <Sender className=\"org.apache.catalina.cluster.tcp.ReplicationTransmitter\"\n                replicationMode=\"fastasyncqueue\"\n                doTransmitterProcessingStats=\"true\"\n                doProcessingStats=\"false\"\n                doWaitAckStats=\"false\"\n                waitForAck=\"false\"\n                keepAliveMaxRequestCount=\"-1\"/>\n\n        <Valve className=\"org.apache.catalina.cluster.tcp.ReplicationValve\"\n               \nfilter=\".*\\.gif;.*\\.js;.*\\.css;.*\\.png;.*\\.jpeg;.*\\.jpg;.*\\.htm;.*\\.html;.*\\.txt;\"\n/>\n\n        <Valve className=\"org.apache.catalina.cluster.session.JvmRouteBinderValve\"\n                enabled=\"true\" />\n\n        <ClusterListener\nclassName=\"org.apache.catalina.cluster.session.ClusterSessionListener\" />\n\n        <ClusterListener\nclassName=\"org.apache.catalina.cluster.session.JvmRouteSessionIDBinderListener\" />\n\n        <Deployer className=\"org.apache.catalina.cluster.deploy.FarmWarDeployer\"\n                tempDir=\"/home/tomcat/polen-integ/tmp/war-temp/\"\n                deployDir=\"${catalina.base}/webapps\"\n                watchDir=\"/home/tomcat/polen-integ/tmp/war-listen/\"\n                watchEnabled=\"true\"/>\n\n        </Cluster>\n\n      </Host>\n    </Engine>\n\n  </Service>\n\n</Server>\n------------------------\n\n\n\nwhen i am trying to deploy a 'dsitributable' (and only when this flag is\nenabled) i get the following errors :\n\n---------------------------\nINFO ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.startup.HostConfig - Deploying web application archive po\nlen.war\n INFO ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.loader.WebappClassLoader - Illegal access: this web appli\ncation instance has been stopped already.  Could not load java.io.PrintStream. \nThe eventual following stack trace is caused by an error t\nhrown for debugging purposes as well as to attempt to terminate the thread which\ncaused the illegal access, and has no functional impact.\n java.lang.IllegalStateException\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1238)\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1198)\n        at java.lang.ClassLoader.loadClassInternal(Unknown Source)\n        at org.apache.log4j.helpers.LogLog.error(LogLog.java:142)\n        at\norg.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:447)\n        at\norg.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:64)\n        at org.apache.log4j.PatternLayout.format(PatternLayout.java:503)\n        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:301)\n        at\norg.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:234)\n        at org.apache.log4j.WriterAppender.append(WriterAppender.java:159)\n        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)\n        at\norg.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)\n        at org.apache.log4j.Category.callAppenders(Category.java:203)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.info(Log4JLogger.java:133)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:976)\n        at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\nINFO ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.loader.WebappClassLoader - Illegal access: this web applic\nation instance has been stopped already.  Could not load java.io.PrintStream. \nThe eventual following stack trace is caused by an error th\nrown for debugging purposes as well as to attempt to terminate the thread which\ncaused the illegal access, and has no functional impact.\n Java.lang.IllegalStateException\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1238)\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1198)\n        at java.lang.ClassLoader.loadClassInternal(Unknown Source)\n        at org.apache.log4j.helpers.LogLog.error(LogLog.java:142)\n        at\norg.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:447)\n        at\norg.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:64)\n        at org.apache.log4j.PatternLayout.format(PatternLayout.java:503)\n        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:301)\n        at\norg.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:234)\n        at org.apache.log4j.WriterAppender.append(WriterAppender.java:159)\n        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:230)\n        at\norg.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:65)\n        at org.apache.log4j.Category.callAppenders(Category.java:203)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.info(Log4JLogger.java:133)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:976)\n at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n        at\norg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)\n        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\nINFO ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.loader.WebappClassLoader - Illegal access: this web applic\nation instance has been stopped already.  Could not load\norg.apache.log4j.spi.VectorWriter.  The eventual following stack trace is caused\nby an error thrown for debugging purposes as well as to attempt to terminate the\nthread which caused the illegal access, and has no functi\nonal impact.\n java.lang.IllegalStateException\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1238)\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1198)\n        at java.lang.ClassLoader.loadClassInternal(Unknown Source)\n        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:154)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:193)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:990)\n        at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n        at\norg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)\n        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\nINFO ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.loader.WebappClassLoader - Illegal access: this web applic\nation instance has been stopped already.  Could not load\norg.apache.log4j.spi.VectorWriter.  The eventual following stack trace is caused\nby an error thrown for debugging purposes as well as to attempt to terminate the\nthread which caused the illegal access, and has no functi\nonal impact.\n java.lang.IllegalStateException\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1238)\n        at\norg.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1198)\n        at java.lang.ClassLoader.loadClassInternal(Unknown Source)\n        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:154)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:193)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:990)\n        at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n        at\norg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)\n        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\nERROR ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.commons.modeler.Registry - Null component Catalina:type=JspMonitor\n,name=jsp,WebModule=//localhost/polen,J2EEApplication=none,J2EEServer=none\n ERROR ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.startup.HostConfig - Error deploying web application arc\nhive polen.war\n java.lang.NoClassDefFoundError: org/apache/log4j/spi/VectorWriter\n        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:154)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:193)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:990)\n        at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n        at\norg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)\n        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\nERROR ContainerBackgroundProcessor[StandardEngine[Catalina]]\norg.apache.catalina.startup.HostConfig - Error deploying web application arch\nive polen.war\n java.lang.NoClassDefFoundError: org/apache/log4j/spi/VectorWriter\n        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:154)\n        at org.apache.log4j.Category.forcedLog(Category.java:388)\n        at org.apache.log4j.Category.log(Category.java:853)\n        at org.apache.commons.logging.impl.Log4JLogger.error(Log4JLogger.java:193)\n        at\norg.apache.catalina.cluster.session.DeltaManager.start(DeltaManager.java:990)\n        at org.apache.catalina.core.ContainerBase.setManager(ContainerBase.java:431)\n        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4125)\n\nat org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)\n        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:739)\n        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:524)\n        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:809)\n        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:698)\n        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472)\n        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1190)\n        at\norg.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:292)\n        at\norg.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)\n        at\norg.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1305)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1569)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1578)\n        at\norg.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1558)\n        at java.lang.Thread.run(Unknown Source)\n---------------\n\ni have tried to deployed via web manager application or simple copy of my war in\nwebapps directory... No luck, if i put '<distributable/> flag in application\nweb.xml config file, i encounter this error ; i need to restart manually tomcat\ninstance... After this restart the application is correctly deployed without any\nerror...\nOf course if i disable cluster in server.xml, no problem...",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "39699",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P2 critical",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "simple deploy failed in cluster (distributable flag)",
    "systemSpecification": true,
    "version": "5.5.17"
}