{
    "comments": [
        {
            "author": "Dominique Pfister",
            "body": "I've noticed this error before refactoring most of FileJournal's code into a base class during resolution of  JCR-702. After having refactored and added some more validations in FileRevision, the error did not show up anymore.\n\nTherefore, setting this bug to fixed, with revision 495239.",
            "date": "2007-01-18T13:35:58.972+0000",
            "id": 0
        }
    ],
    "component": "jackrabbit-core",
    "description": "The following exception stack traces appearing repeatedly during a performance test of a JCR cluster at a customer site. \n\nERROR - Unexpected error while preparing log entry.\njava.lang.NullPointerException\n\tat org.apache.jackrabbit.core.cluster.FileRevision.unlock(FileRevision.java:117)\n\tat org.apache.jackrabbit.core.cluster.FileRevision.get(FileRevision.java:146)\n\tat org.apache.jackrabbit.core.cluster.FileJournal.sync(FileJournal.java:296)\n\tat org.apache.jackrabbit.core.cluster.FileJournal.begin(FileJournal.java:435)\n\tat org.apache.jackrabbit.core.cluster.ClusterNode.updatePrepared(ClusterNode.java:399)\n\tat org.apache.jackrabbit.core.cluster.ClusterNode.access$000(ClusterNode.java:40)\n\tat org.apache.jackrabbit.core.cluster.ClusterNode$WorkspaceUpdateChannel.updatePrepared(ClusterNode.java:559)\n\tat org.apache.jackrabbit.core.state.SharedItemStateManager$Update.begin(SharedItemStateManager.java:647)\n\tat org.apache.jackrabbit.core.state.SharedItemStateManager.beginUpdate(SharedItemStateManager.java:778)\n\tat org.apache.jackrabbit.core.state.SharedItemStateManager.update(SharedItemStateManager.java:808)\n\tat org.apache.jackrabbit.core.state.LocalItemStateManager.update(LocalItemStateManager.java:326)\n\tat org.apache.jackrabbit.core.state.XAItemStateManager.update(XAItemStateManager.java:313)\n\tat org.apache.jackrabbit.core.state.LocalItemStateManager.update(LocalItemStateManager.java:302)\n\tat org.apache.jackrabbit.core.state.SessionItemStateManager.update(SessionItemStateManager.java:295)\n\tat org.apache.jackrabbit.core.ItemImpl.save(ItemImpl.java:1204)\n\tat org.apache.jackrabbit.core.SessionImpl.save(SessionImpl.java:821)\n\t\nERROR - Unexpected error while committing log entry.\njava.lang.NullPointerException\n\tat org.apache.jackrabbit.core.cluster.FileJournal.commit(FileJournal.java:660)\n\tat org.apache.jackrabbit.core.cluster.ClusterNode.updateCommitted(ClusterNode.java:425)\n\tat org.apache.jackrabbit.core.cluster.ClusterNode$WorkspaceUpdateChannel.updateCommitted(ClusterNode.java:566)\n\tat org.apache.jackrabbit.core.state.SharedItemStateManager$Update.end(SharedItemStateManager.java:712)\n\tat org.apache.jackrabbit.core.state.SharedItemStateManager.update(SharedItemStateManager.java:808)\n\tat org.apache.jackrabbit.core.state.LocalItemStateManager.update(LocalItemStateManager.java:326)\n\tat org.apache.jackrabbit.core.state.XAItemStateManager.update(XAItemStateManager.java:313)\n\tat org.apache.jackrabbit.core.state.LocalItemStateManager.update(LocalItemStateManager.java:302)\n\tat org.apache.jackrabbit.core.state.SessionItemStateManager.update(SessionItemStateManager.java:295)\n\tat org.apache.jackrabbit.core.ItemImpl.save(ItemImpl.java:1204)\n\tat org.apache.jackrabbit.core.SessionImpl.save(SessionImpl.java:821)\n\t",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "JCR-712",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "Major",
    "product": "JACKRABBIT",
    "project": "JACKRABBIT",
    "summary": "NPE Exception Thrown By FileJournal During Commit Operation",
    "systemSpecification": true,
    "version": "1.2.1"
}